version: '3.8'

services:
  flask-app:
    build:
      context: .
    ports:
      - "3000:3000"
    volumes:
      - ./prometheus:/prometheus
    networks:
      - my_network
  otp:
    image: opentripplanner/opentripplanner:2.7.0_2024-11-26T16-34
    command: ["--load", "--serve"]
    ports:
      - "8080:8080"
    environment:
      JAVA_TOOL_OPTIONS: "-Xmx8g"
    volumes:
      - ./network:/var/opentripplanner
    networks:
      - my_network

networks:
  my_network:
    external: true